app:
    resource: "@AppBundle/Controller/"
    type:     annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

UrlREST:
    resource:   "@AppBundle/Controller/UrlRESTController.php"
    type:       rest
    prefix:     /api

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
