<?php

namespace AppBundle\Entity;

/**
 * TestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UrlRepository extends \Doctrine\ORM\EntityRepository
{
    public function findTotalMatches($keyword)
    {
        /* your awesome code block */
        return 56;
    }
}
